/*
'use strict';

const pusherRepoRawCommits = [
  {
    "repo":"pusher-http-ruby",
    "user":"adamwiggins",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"lporras",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"jdudek",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"craigerm",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"nicolasleger",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"SebastianEdwards",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"kieranklaassen",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"tricknotes",
    "num_commits":1
  },
  {
    "repo":"pusher-http-ruby",
    "user":"maryrosecook",
    "num_commits":2
  },
  {
    "repo":"pusher-http-ruby",
    "user":"timherby",
    "num_commits":2
  },
  {
    "repo":"pusher-http-ruby",
    "user":"miksago",
    "num_commits":2
  },
  {
    "repo":"pusher-http-ruby",
    "user":"vivangkumar",
    "num_commits":2
  },
  {
    "repo":"pusher-http-ruby",
    "user":"KevinSjoberg",
    "num_commits":3
  },
  {
    "repo":"pusher-http-ruby",
    "user":"benpickles",
    "num_commits":3
  },
  {
    "repo":"pusher-http-ruby",
    "user":"toshi3221",
    "num_commits":3
  },
  {
    "repo":"pusher-http-ruby",
    "user":"maxthelion",
    "num_commits":3
  },
  {
    "repo":"pusher-http-ruby",
    "user":"joshk",
    "num_commits":4
  },
  {
    "repo":"pusher-http-ruby",
    "user":"olly",
    "num_commits":4
  },
  {
    "repo":"pusher-http-ruby",
    "user":"hamchapman",
    "num_commits":5
  },
  {
    "repo":"pusher-http-ruby",
    "user":"DanielWaterworth",
    "num_commits":5
  },
  {
    "repo":"pusher-http-ruby",
    "user":"markburns",
    "num_commits":5
  },
  {
    "repo":"pusher-http-ruby",
    "user":"fujimura",
    "num_commits":6
  },
  {
    "repo":"pusher-http-ruby",
    "user":"mdpye",
    "num_commits":6
  },
  {
    "repo":"pusher-http-ruby",
    "user":"jackfranklin",
    "num_commits":10
  },
  {
    "repo":"pusher-http-ruby",
    "user":"zimbatm",
    "num_commits":12
  },
  {
    "repo":"pusher-http-ruby",
    "user":"wildfalcon",
    "num_commits":14
  },
  {
    "repo":"pusher-http-ruby",
    "user":"pl",
    "num_commits":15
  },
  {
    "repo":"pusher-http-ruby",
    "user":"ismasan",
    "num_commits":25
  },
  {
    "repo":"pusher-http-ruby",
    "user":"mloughran",
    "num_commits":213
  },
  {
    "repo":"pusher-js",
    "user":"lukeholder",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"jackfranklin",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"Klaasvaak",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"maxthelion",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"vivangkumar",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"guiocavalcanti",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"tristandunn",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"pborreli",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"cedrichan",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"addbrick",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"abaran",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"loris",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"viniciussbs",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"intale",
    "num_commits":1
  },
  {
    "repo":"pusher-js",
    "user":"tiemevanveen",
    "num_commits":2
  },
  {
    "repo":"pusher-js",
    "user":"dirkbonhomme",
    "num_commits":4
  },
  {
    "repo":"pusher-js",
    "user":"zimbatm",
    "num_commits":9
  },
  {
    "repo":"pusher-js",
    "user":"wildfalcon",
    "num_commits":11
  },
  {
    "repo":"pusher-js",
    "user":"leggetter",
    "num_commits":15
  },
  {
    "repo":"pusher-js",
    "user":"benpickles",
    "num_commits":21
  },
  {
    "repo":"pusher-js",
    "user":"DanielWaterworth",
    "num_commits":21
  },
  {
    "repo":"pusher-js",
    "user":"miksago",
    "num_commits":43
  },
  {
    "repo":"pusher-js",
    "user":"ismasan",
    "num_commits":72
  },
  {
    "repo":"pusher-js",
    "user":"maryrosecook",
    "num_commits":120
  },
  {
    "repo":"pusher-js",
    "user":"mloughran",
    "num_commits":136
  },
  {
    "repo":"pusher-js",
    "user":"pl",
    "num_commits":674
  },
  {
    "repo":"pusher-http-python",
    "user":"zbyte64",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"tomekwojcik",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"remoun",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"aaronsw",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"nicholasserra",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"philippbosch",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"tesdal",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"vetal4444",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"onyxfish",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"mbrrg",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"henryl",
    "num_commits":1
  },
  {
    "repo":"pusher-http-python",
    "user":"vivienschilis",
    "num_commits":2
  },
  {
    "repo":"pusher-http-python",
    "user":"iurisilvio",
    "num_commits":2
  },
  {
    "repo":"pusher-http-python",
    "user":"brendoncrawford",
    "num_commits":2
  },
  {
    "repo":"pusher-http-python",
    "user":"rdpfeffer",
    "num_commits":2
  },
  {
    "repo":"pusher-http-python",
    "user":"martynsmith",
    "num_commits":2
  },
  {
    "repo":"pusher-http-python",
    "user":"rasky",
    "num_commits":3
  },
  {
    "repo":"pusher-http-python",
    "user":"maryrosecook",
    "num_commits":3
  },
  {
    "repo":"pusher-http-python",
    "user":"leggetter",
    "num_commits":17
  },
  {
    "repo":"pusher-http-python",
    "user":"pablobm",
    "num_commits":24
  },
  {
    "repo":"pusher-http-python",
    "user":"DanielWaterworth",
    "num_commits":25
  },
  {
    "repo":"pusher-http-python",
    "user":"jpatel531",
    "num_commits":29
  },
  {
    "repo":"pusher-http-python",
    "user":"zimbatm",
    "num_commits":51
  },
  {
    "repo":"backbone-todo-app",
    "user":"hamchapman",
    "num_commits":4
  },
  {
    "repo":"backbone-todo-app",
    "user":"maryrosecook",
    "num_commits":6
  },
  {
    "repo":"backbone-todo-app",
    "user":"miksago",
    "num_commits":31
  },
  {
    "repo":"realtime_survey_complete",
    "user":"leggetter",
    "num_commits":5
  },
  {
    "repo":"pusher-presence-demo",
    "user":"miksago",
    "num_commits":1
  },
  {
    "repo":"pusher-presence-demo",
    "user":"maxthelion",
    "num_commits":6
  },
  {
    "repo":"pusher-presence-demo",
    "user":"benpickles",
    "num_commits":7
  },
  {
    "repo":"pusher-presence-demo",
    "user":"maryrosecook",
    "num_commits":11
  },
  {
    "repo":"pusher-presence-demo",
    "user":"mloughran",
    "num_commits":39
  },
  {
    "repo":"backpusher",
    "user":"miksago",
    "num_commits":1
  },
  {
    "repo":"backpusher",
    "user":"mkdynamic",
    "num_commits":1
  },
  {
    "repo":"backpusher",
    "user":"codezomb",
    "num_commits":1
  },
  {
    "repo":"backpusher",
    "user":"maryrosecook",
    "num_commits":4
  },
  {
    "repo":"pusher-test",
    "user":"mdpye",
    "num_commits":1
  },
  {
    "repo":"pusher-test",
    "user":"vivangkumar",
    "num_commits":2
  },
  {
    "repo":"pusher-test",
    "user":"aschuch",
    "num_commits":2
  },
  {
    "repo":"pusher-test",
    "user":"leggetter",
    "num_commits":2
  },
  {
    "repo":"pusher-test",
    "user":"zimbatm",
    "num_commits":3
  },
  {
    "repo":"pusher-test",
    "user":"hamchapman",
    "num_commits":4
  },
  {
    "repo":"pusher-test",
    "user":"maryrosecook",
    "num_commits":10
  },
  {
    "repo":"pusher-test",
    "user":"pl",
    "num_commits":46
  },
  {
    "repo":"pusher-test",
    "user":"mloughran",
    "num_commits":55
  },
  {
    "repo":"spacegame_example",
    "user":"miksago",
    "num_commits":6
  },
  {
    "repo":"spacegame_example",
    "user":"dctanner",
    "num_commits":18
  },
  {
    "repo":"notify",
    "user":"longkt90",
    "num_commits":1
  },
  {
    "repo":"pusher-node-server",
    "user":"pl",
    "num_commits":1
  },
  {
    "repo":"pusher-node-server",
    "user":"alram",
    "num_commits":1
  },
  {
    "repo":"pusher-node-server",
    "user":"lafikl",
    "num_commits":1
  },
  {
    "repo":"pusher-node-server",
    "user":"dctanner",
    "num_commits":1
  },
  {
    "repo":"pusher-node-server",
    "user":"mdpye",
    "num_commits":2
  },
  {
    "repo":"pusher-node-server",
    "user":"crossbreeze",
    "num_commits":4
  },
  {
    "repo":"pusher-node-server",
    "user":"leggetter",
    "num_commits":23
  },
  {
    "repo":"filtrand",
    "user":"pl",
    "num_commits":5
  },
  {
    "repo":"filtrand",
    "user":"mloughran",
    "num_commits":11
  },
  {
    "repo":"filtrand",
    "user":"maryrosecook",
    "num_commits":71
  },
  {
    "repo":"pusher-realtime-data",
    "user":"leggetter",
    "num_commits":2
  },
  {
    "repo":"titanium_pusher_ios",
    "user":"rubenfonseca",
    "num_commits":11
  },
  {
    "repo":"titanium_pusher_android",
    "user":"rubenfonseca",
    "num_commits":8
  },
  {
    "repo":"icanhazissues",
    "user":"DanielWaterworth",
    "num_commits":7
  },
  {
    "repo":"icanhazissues",
    "user":"mdpye",
    "num_commits":11
  },
  {
    "repo":"icanhazissues",
    "user":"zimbatm",
    "num_commits":20
  },
  {
    "repo":"icanhazissues",
    "user":"mloughran",
    "num_commits":20
  },
  {
    "repo":"icanhazissues",
    "user":"maxthelion",
    "num_commits":65
  },
  {
    "repo":"html5-realtime-push-notifications",
    "user":"robhawkes",
    "num_commits":7
  },
  {
    "repo":"html5-realtime-push-notifications",
    "user":"leggetter",
    "num_commits":19
  },
  {
    "repo":"html5-realtime-activity-streams",
    "user":"robhawkes",
    "num_commits":8
  },
  {
    "repo":"html5-realtime-activity-streams",
    "user":"leggetter",
    "num_commits":12
  },
  {
    "repo":"cognac.js",
    "user":"miksago",
    "num_commits":2
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"unthunk",
    "num_commits":1
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"samuel-queniart",
    "num_commits":1
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"zimbatm",
    "num_commits":1
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"HarveyEV",
    "num_commits":1
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"Jonwheeler",
    "num_commits":2
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"whirish",
    "num_commits":3
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"robhawkes",
    "num_commits":7
  },
  {
    "repo":"pusher-realtime-chat-widget",
    "user":"leggetter",
    "num_commits":22
  },
  {
    "repo":"marbles",
    "user":"dctanner",
    "num_commits":1
  },
  {
    "repo":"marbles",
    "user":"pl",
    "num_commits":6
  },
  {
    "repo":"marbles",
    "user":"maryrosecook",
    "num_commits":8
  },
  {
    "repo":"ruby-protobuf",
    "user":"rtecco",
    "num_commits":1
  },
  {
    "repo":"ruby-protobuf",
    "user":"mperham",
    "num_commits":1
  },
  {
    "repo":"ruby-protobuf",
    "user":"pl",
    "num_commits":2
  },
  {
    "repo":"ruby-protobuf",
    "user":"vivrass",
    "num_commits":6
  },
  {
    "repo":"ruby-protobuf",
    "user":"technohippy",
    "num_commits":128
  },
  {
    "repo":"ruby-protobuf",
    "user":"macks",
    "num_commits":155
  },
  {
    "repo":"realtime-commenting",
    "user":"leggetter",
    "num_commits":6
  },
  {
    "repo":"pusher-realtime-thermometer",
    "user":"leggetter",
    "num_commits":2
  },
  {
    "repo":"pusher-js-diagnostics",
    "user":"pl",
    "num_commits":1
  },
  {
    "repo":"pusher-js-diagnostics",
    "user":"hamchapman",
    "num_commits":6
  },
  {
    "repo":"pusher-js-diagnostics",
    "user":"leggetter",
    "num_commits":19
  },
  {
    "repo":"web-socket-js",
    "user":"3rd-Eden",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"BonsaiDen",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"jamadden",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"abonec",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"stefanaxelsson",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"imanel",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"cgbystrom",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"benpickles",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"jvshahid",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"doenietzomoeilijk",
    "num_commits":1
  },
  {
    "repo":"web-socket-js",
    "user":"wtritch",
    "num_commits":2
  },
  {
    "repo":"web-socket-js",
    "user":"luciferous",
    "num_commits":2
  },
  {
    "repo":"web-socket-js",
    "user":"rauchg",
    "num_commits":2
  },
  {
    "repo":"web-socket-js",
    "user":"kanaka",
    "num_commits":2
  },
  {
    "repo":"web-socket-js",
    "user":"sleavitt",
    "num_commits":3
  },
  {
    "repo":"web-socket-js",
    "user":"pl",
    "num_commits":4
  },
  {
    "repo":"web-socket-js",
    "user":"mcav",
    "num_commits":4
  },
  {
    "repo":"web-socket-js",
    "user":"gimite",
    "num_commits":109
  },
  {
    "repo":"realtime-visitor-tracker",
    "user":"leggetter",
    "num_commits":6
  },
  {
    "repo":"realtime-web-workshop",
    "user":"leggetter",
    "num_commits":18
  },
  {
    "repo":"html5-hacks-thermometer",
    "user":"leggetter",
    "num_commits":3
  },
  {
    "repo":"pusher-phonegap-android",
    "user":"marknadig",
    "num_commits":1
  },
  {
    "repo":"pusher-phonegap-android",
    "user":"rdpfeffer",
    "num_commits":1
  },
  {
    "repo":"pusher-phonegap-android",
    "user":"albertut",
    "num_commits":1
  },
  {
    "repo":"pusher-phonegap-android",
    "user":"leggetter",
    "num_commits":13
  }
];


const pusherCommunityRawCommits = {
  "hackauthon": {"jpatel531": 14},
  "pusher-revealjs-remote-server": {"leggetter": 7},
  "pusher-php-silex": {"leggetter": 19, "jonmountjoy": 18, "mbren": 1, "dzuelke": 2},
  "pusher-websocket-ruby": {"mloughran": 16, "vivangkumar": 1, "mdpye": 1, "Aaron1011": 4, "leggetter": 7, "rkh": 3, "logankoester": 22, "njh": 1, "Intrepidd": 1, "nightpool": 1, "tmecklem": 1, "pat": 15, "emnl": 3, "jarthod": 3, "zimbatm": 22, "fukayatsu": 1, "krisleech": 1, "glenngillen": 8, "Juanmcuello": 1, "jrozner": 4},
  "pusher-http-perl": {"squeeks": 34, "carcus88": 3},
  "real-time-laravel-app": {"leggetter": 8},
  "pusher-revealjs-remote": {"leggetter": 7},
  "pusher-js-npm-basics": {"leggetter": 5},
  "real-time-laravel": {"leggetter": 56, "Francismori7": 1, "AaronO": 1, "vinkla": 1, "drbyte": 6},
  "pusher-websocket-dotnet": {"RobertoSchneiders": 1, "leggetter": 20, "mchandschuh": 1},
  "gs-pusher-node": {"leggetter": 5, "jackfranklin": 2},
  "pusher-js-test-stub": {"leggetter": 20, "rib3": 1, "kjcpaas": 2, "jbescoyez": 1},
  "pusher-realtime-producthunt-extension": {"leggetter": 4, "robhawkes": 15},
  "gs-pusher-rails": {"jackfranklin": 8},
  "realtime-twitter-search-angular2": {"NathanWalker": 2, "jackfranklin": 16},
  "pusher-jspm-es6": {"jackfranklin": 4},
  "gs-pusher-ios": {"leggetter": 8},
  "pusher-realtime-reddit": {"robhawkes": 37},
  "pusher-realtime-producthunt": {"mdpye": 1, "robhawkes": 12},
  "pusher-http-rust": {"jpatel531": 63},
  "gs-pusher-aspnet-mvc5": {"leggetter": 6},
  "pusher-websocket-go": {"zimbatm": 1, "mloughran": 2, "jpatel531": 14},
  "pusher-realtime-reddit-demo": {"jackfranklin": 1, "robhawkes": 9},
  "pusher-datasource-api": {"jackfranklin": 17},
  "pusher-http-haskell": {"WillSewell": 71, "passy": 1},
  "react-realtime-chat": {"leggetter": 3, "jpatel531": 8},
  "emberjs-realtime-chat": {"jackfranklin": 17},
  "sinatra-realtime-server": {"jackfranklin": 7},
  "gs-pusher-php-no-framework": {"leggetter": 17},
  "pusher-twitter-streamer": {"leggetter": 1, "jackfranklin": 8}
};

const pusherEngineers = [
  'DanielWaterworth',
  'Nicowcow',
  'WillSewell',
  'alexpate',
  'benfoxall',
  'ewmy',
  'frogvalley',
  'hamchapman',
  'jackfranklin',
  'jamescun',
  'jpatel531',
  'leggetter',
  'maryrosecook',
  'maxthelion',
  'mdpye',
  'mloughran',
  'olgad123',
  'olgagithub',
  'pl',
  'pusher-ci',
  'pusher-dashboard',
  'pusher-puppet',
  'robhawkes',
  'seeemilyplay',
  'stealthpig',
  'sylg',
  'topliceanu',
  'vivangkumar',
  'zimbatm',
];


// Correctly format the users and their commits. {user: count_commits}
const userCommits = pusherRepoRawCommits.reduce((collector, item) => {
  if (!collector[item.user]) {
    collector[item.user] = 0;
  }
  collector[item.user] += item.num_commits;
  return collector;
}, {});

// Add contributions from pusher-community.
Object.keys(pusherCommunityRawCommits).forEach((repo) => {
  Object.keys(pusherCommunityRawCommits[repo]).forEach((username) => {
    const numCommits = pusherCommunityRawCommits[repo][username];
    if (!userCommits[username]) {
      userCommits[username] = 0;
    }
    userCommits[username] += numCommits;
  });
});

// Filter out pusher past and present engineers.
pusherEngineers.forEach((username) => {
  if (userCommits[username]) {
    delete userCommits[username];
  }
});

const tableData = Object.keys(userCommits).map((username, index) => {
  const numCommits = userCommits[username];
  return template(index+1, username, numCommits);
}).join('');

document.querySelector('#leaderboard tbody').innerHTML = tableData;

var table = document.getElementById('leaderboard');
Sortable.init(table);
*/
